### PR TITLE
Install macOS AT Driver server from npm

### PR DESCRIPTION
**Pull request by jugglinmike**
This package was published to npm today, and the latest version includes a recent fix for issues with simulating pressing of the "Shift" key.

### CODE REVIEW

**Comment by gnarf** [comment]
+ @outofambit as review as she's likely taking over this work, and this change will need to be updated in the azure pipeline macos work as well

**Review by gnarf — CHANGES_REQUESTED** [review]
I think this might need a path update in run-tester.sh as well.  It [failed](https://github.com/bocoup/aria-at-gh-actions-helper/actions/runs/11042592022/job/30675327081#step:21:15) when I tried to run the job from this branch.

**Review by gnarf — APPROVED** [review]
LGTM

**Comment by gnarf** [comment]
One thought I had, we might want to copy the [nvda_version](https://github.com/bocoup/aria-at-gh-actions-helper/blob/main/.github/workflows/nvda-test.yml#L49) pattern and make the at-driver-version a param that defaults to "~0.6.0" (so you can test current workflow against a specific release beta) but I leave the final call on that to you @jugglinmike

**Comment by gnarf** [comment]
https://github.com/bocoup/aria-at-gh-actions-helper/wiki/20240926-0600.consistency-report was run against this branch (I pushed it to gnarf/main before running this collection) so it got about 220 successful runs :)

**Review by outofambit — APPROVED** [review]
looks great, glad we are making this improvement to the install process!

**Comment by jugglinmike** [comment]
> One thought I had, we might want to copy the [nvda_version](https://github.com/bocoup/aria-at-gh-actions-helper/blob/main/.github/workflows/nvda-test.yml#L49) pattern and make the at-driver-version a param that defaults to "~0.6.0" (so you can test current workflow against a specific release beta) but I leave the final call on that to you @jugglinmike

Couldn't hurt. Would you mind taking another look, @gnarf?

**Review by gnarf — APPROVED** [review]
Nice - Landing it

**Pull request merged**
